### ISSUE TITLE
GIS2BIM.WMTSTileListFromBbox kan ook zonder Points

### ISSUE THREAD

**Issue by ekkonap** [DutchSailor/GIS2BIM#13]
Gebruik List.OfRepeatedItem, gaat wat sneller.

tileSize=PixelWidth*MetersPerPixel;
nTiles=Math.Ceiling(bbox/tileSize);
n=Math.Ceiling(nTiles/2)*2;
//rond nTiles af naar groter even getal, zodat het straks door 2 deelbaar is;

i=n+1;
//aantal tegels;

uniqueTileColumns=(TileColumn-(n/2))..(TileColumn+(n/2))..#i;
uniqueTileRows=(TileRow-(n/2))..(TileRow+(n/2))..#i;
tileColumns=Flatten(List.OfRepeatedItem(uniqueTileColumns,i));
tileRows=Flatten(List.OfRepeatedItem(uniqueTileRows<1L>,i));
nt=i*i;
totalWidth=tileSize*i;

**Comment by DutchSailor** [comment]
Top plan! In versie 0.9 is deze verbetering meegenomen. Superbedankt voor je input!
