### ISSUE TITLE
meer dan 1000 objecten

### ISSUE THREAD

**Issue by jochem25** [DutchSailor/GIS2BIM#15]
het blijkt dat je bij pdok maximaal van 1000 objecten informatie per keer kunt opvragen. Evt kun je met wfs 2.0 meer opvragen maar dat moet dan in batches:
https://www.brentjensgeoict.nl/2014/01/29/haal-meer-data-en-geojson-uit-een-pdok-wfs/
Ik heb nog niet gekeken om hier iets voor te maken, maar het zou een leuke uitbreiding kunnen zijn.

**Comment by jochem25** [comment]
![image](https://user-images.githubusercontent.com/33322339/65274338-5e10ac00-db23-11e9-8813-ca3c85be7c5c.png)
dit is denk ik een simpele oplossing.

**Comment by jochem25** [comment]
sommige nodes hebben alleen de web request opgenomen, deze zou m.i. idealiter los moeten zijn zoals bij bovenstaand voorbeeld.

**Comment by DutchSailor** [comment]
Deze is nu toegevoegd aan GIS2BIM! Gemaakt door jou!
