### ISSUE TITLE
geluidscontouren

### ISSUE THREAD

**Issue by jochem25** [DutchSailor/GIS2BIM#17]
ik gebruik vaak een kaartje voor de geluidscontouren:

GIS2BIM.GeoservicesLibraryNetherland:

"http://geodata.rivm.nl/";
"geoserver/alo/wms??";
"&request=GetMap";
"&VERSION=1.3.0";
"&STYLES=rivm_20180205_g_geluidkaart_lden_alle_bronnen";
"&layers=rivm_20180205_g_geluidkaart_lden_wegverkeer";
"&bbox=";
"&width=2000";
"&height=2000";
"&format=image/png";
"&crs=EPSG:28992";

[GIS2BIM.GeoservicesLibraryNetherland_geluidscontouren.zip](https://github.com/DutchSailor/GIS2BIM/files/3206657/GIS2BIM.GeoservicesLibraryNetherland_geluidscontouren.zip)

misschien een idee om toe te voegen

**Comment by DutchSailor** [comment]
Hoi Jochem,

thanks for this advice. Very nice sever. The server is added to future version 0.9

kind regards
