### ISSUE TITLE
Node 0.11.0 not available in Dynamo package manager 

### ISSUE THREAD

**Issue by gdemol** [DutchSailor/GIS2BIM#19]
It seems like the new nodes cannot be downloaded (yet) from the Dynamo package manager:

![image](https://user-images.githubusercontent.com/17804567/77238488-b3ac3b00-6bd0-11ea-9899-0c973af25e76.png)

I am still on 0.10.0. Looking forward to 0.11.0!

**Comment by DutchSailor** [comment]
Hi Gerard, GIS2BIM is the package for Dynamo 1.x. It is not longer maintained. The new package is 'GIS2BIM for Dynamo 2.x'. Here you can download the last version of GIS2BIM.
