### ISSUE TITLE
Adres is niet altijd bekend of relevant

### ISSUE THREAD

**Issue by ekkonap** [DutchSailor/GIS2BIM#2]
Hoi Maarten,
Ik ben nu je werk aan het bekijken. Het eerste dat me opvalt (en om het githubby te doen, maak ik daar dan maar het eerste issue van): nieuwbouwprojecten hebben niet altijd een adres. Laat de webserver van PDOK ook input toe in de vorm van RD- of WGS984-coordinaten die niet binnen een bestaande registratie vallen?

Ik kan me een node voorstellen die voor de gebruiker een soort interface opent om een punt op een kaart aan te klikken. Dat kan zo simpel zijn als een pop-up met een hyperlink naar PDOK viewer en de instructie om de x- en y- coördinaten van de gewenste locatie te lezen en in te vullen.

Of heb je die node al en kijk ik er over heen?

**Comment by DutchSailor** [comment]
Hi Ekko,

you can use the Revit-Location as well and transform the LAT/LON.

regards Maarten
![image](https://user-images.githubusercontent.com/30430941/31885247-21d75bc4-b7f0-11e7-8aaa-89517d1010d2.png)

**Comment by ekkonap** [comment]
Elegant. Could not find the GIS2BIM.CoordinateReferenceSystemsLibrary(CRS) in the package however. Still in testing? Never mind, already made my own a while back. So that will give me a list of items in a bounding box. I think it is also possible to put the lon/lat in a webrequest and get the nearest item. Not sure if that is useful though. I wonder what happens if the bounding box is too small for any items to fit in.
Is there a way to set the sitelocation object in the API? I haven't been able to find an example.

**Comment by ekkonap** [comment]
Hi Martin,
That approach lets me query the kadaster, but there is no information about adresses there. Any way to query the locatieserver directly with a point or bounding box? Couln't find any in the pdok api docs. No way to get from a kadaster perceel to an adress either? Did look for one, no luck.

**Comment by DutchSailor** [comment]
Hi Ekko,

the GIS2BIM.CoordinateReferenceSystemsLibrary(CRS) is in the version 0.4 folder. This one is not released yet, you can download it from [https://github.com/DutchSailor/GIS2BIM/tree/master/nodes/0.4]
About the sitelocation. It can be changed. Good idea for a new node!
[http://www.revitapidocs.com/2015/9d71159d-514c-c1b3-8673-5c0e7f28b688.htm]

About the BAG, I will have a closer look to that,

**Comment by ekkonap** [comment]
I found a way to build a suggestion query to act as an interpreter between the UI input and the free query node you made. This first version just picks the top ranking suggestion, but the other result can be made available in a dropdown list in data-shapes. I'll post my script later.
Is that revitapidoc example still valid? It's for the 2015 api, and the later references looked different I think. Would be nice though!

**Comment by ekkonap** [comment]
Ok, managed to make a node for setting the sitelocation properties. Works like a charm. Starting to get the hang of python and the revit api, translating the revitapidocs to python without any programming skills is hard! Server is down for the weekend, will try to upload to github next week.

**Comment by DutchSailor** [comment]
Fantastic!! Looking forward to it!

2017-11-03 17:24 GMT+01:00 ekkonap <notifications@github.com>:

**Comment by DutchSailor** [comment]
Added to version 0.4
