### ISSUE TITLE
Importen afbeeldingen Revit 2021

### ISSUE THREAD

**Issue by MarcelP102** [DutchSailor/GIS2BIM#21]
Zie dat jullie de scripts met Revit 2020 testen. Heb helaas inmiddels al Revit 2021 ingericht voor gebruik en daarbij werken de scripts niet. Zo worden onderleggers wel gedownload maar niet geïmporteerd. Mogelijk komt dit door de obsolete api's? https://www.revitapidocs.com/2020/04484b9c-093c-6306-2d2c-d2307675b615.htm

Bij de Kadaster+2D bag worden alleen de kadastrale lijnen geïmporteerd. 3D lijkt vooralsnog helemaal niet te werken.

Het ziet er fantastisch uit! Hoop dat 2021 ook ondersteund gaat worden.

**Comment by Teun1** [comment]
De API voor R2021 is gewijzigd voor het plaatsen van images.
In een pull request is een voorstel gedaan voor verbetering.

**Comment by DutchSailor** [comment]
Inmiddels verwerkt in 0.11.14
