### ISSUE TITLE
kadaster v3 update naar v4

### ISSUE THREAD

**Issue by jochem25** [DutchSailor/GIS2BIM#24]
de kadaster wfs service lijkt een update te hebben gehad naar v4, ik kan zelfs het script met v3 niet meer gebruiken (404 error).

dit is iig de link voor v4 perceelgrenzen
"http://geodata.nationaalgeoregister.nl/";
"kadastralekaart/wfs/v4_0?service=WFS&version=2.0.0";
"&request=GetFeature";
"&typeName=kadastralekaartv4:kadastralegrens";
"&bbox=";

**Comment by DutchSailor** [comment]
Ha Jochem, 

Dank! In de laatste versie deze wijziging meegenomen,
