### ISSUE TITLE
Dead link in implementatiehandleiding

### ISSUE THREAD

**Issue by MRL-33** [DutchSailor/GIS2BIM#26]
Ik zie een dode link in de implementatiehandleiding. De afbeelding kan niet worden weergegeven. Kunt u deze herstellen?
[https://github.com/DutchSailor/GIS2BIM/wiki/Implementatiehandleiding](url)
![IMPLEMENTATIE](https://user-images.githubusercontent.com/59490465/117585070-bccbd480-b110-11eb-9642-cf1439e4a3dc.png)

**Comment by DutchSailor** [comment]
It should work now.
