### ISSUE TITLE
3DBAG - Revit only showing blue preview lines but no mass is placed

### ISSUE THREAD

**Issue by Rellert** [DutchSailor/GIS2BIM#28]
Hi @DutchSailor,

I am running into some issues with the 3DBAG script.
Somehow it doesn't give me any errors on most areas (some do give errors, f.e. : "null value cannot be cast to double" in the first part of group "create solid geometry")

Anyhow, i only end up getting blue lines inside Revit and once i close dynamo the blue lines disappear (obviously because they are preview lines..). So the script is getting the right data from filled-in area, but it somehow fails to create a solid out of it.
Perhaps I'm doing something wrong here (missing a step probably).

Maybe you can help me solve this problem!

Thanks in advance.

kind regards,
Martijn

![error messages](https://user-images.githubusercontent.com/99867916/154451192-ae88dec8-82c8-4ef1-869a-da92cbb92950.PNG)
![result dynamo 3DBAG](https://user-images.githubusercontent.com/99867916/154451196-87fc756d-32ba-4697-82a8-33a6585e1671.PNG)
![result Revit 3DBAG](https://user-images.githubusercontent.com/99867916/154451198-7a44b935-afec-45ec-8e23-74344ca00f65.PNG)

**Comment by DutchSailor** [comment]
Hi Martijn,
There might be some errors at the beginning to corrupt geometry.
But it should not be a problem to place the masses.
When I look at your script the last node is frozing. So perhaps that’s the reasing why you do not see them.

It is also possible the in de view settings masses are invisible.

kind regards

Maarten
