### ISSUE TITLE
geen scheiding tussen nodes die info ophalen en nodes die Revit editen

### ISSUE THREAD

**Issue by ekkonap** [DutchSailor/GIS2BIM#3]
Item 2: ik kom bijvoorbeeld bij de node GIS2BIM.WebrequestWMS tegen dat in één moeite door een image downloaden en in Revit zetten. In mijn geval doet dat laatste stukje het nu even niet, waarschijnlijk wel te verhelpen. Maar stel nou dat ik met dat image iets heel anders wil doen dan in een view laden? Of dat voor 1 van beide de benodigde input wijzigt (PDOK of Revit API update)? Ik zou zeggen, probeer functies op te splitsen en dan in 'hogere' nodes of voorbeeldscripts bij elkaar te brengen.
Of had je juist een bepaalde bedoeling met het samenvoegen?

Als mijn eerste bijdrage een versie van GIS2BIM.WebrequestWMS zonder GIS2BIM.ImportImageInView
[OOA.GIS2BIM.WebrequestWMS.dyf.zip](https://github.com/DutchSailor/GIS2BIM/files/1398030/OOA.GIS2BIM.WebrequestWMS.dyf.zip)

Ik ben niet heel erg thuis in Github. Ik heb net een fork gemaakt, maar daarna zie ik even niet hoe ik de versie van jouw node kan vinden om te vervangen voor mijn versie. Komt een ander keertje wel.

**Comment by DutchSailor** [comment]
Good point. An extra node is added to version 0.4
