### ISSUE TITLE
Workflow has dependency's

### ISSUE THREAD

**Issue by ChemicalNRG** [DutchSailor/GIS2BIM#30]
Workflow needs Data-Shapes package to work propperly, at least Workflows 2.x Nederland.
Maybe you could at this in the Wiki? Because this is not clear without diving in the nodes.

So maybe a check and error message is even better

Edit: It also needs Clockwork for Dynamo 2.x 2.4.0, DynamoIronPython2.7, MeshToolkit, spring nodes

Edit 2: Found the handleiding today which mentions the needed packages (except IronPython),
Maybe you can add a link to that on the main readme? Also the implementatiehandleiding is maybe confusing?

I know, it was all there, i did not read enough haha. But in my defence, when searching it finding this through google, it is not that clear, especially since not a lot of github projects have a Wiki, just a readme, and github does not do a good job of highlighting the Wiki when there is one.

**Comment by DutchSailor** [comment]
Thanks for you message! The dutch manual can be found here: https://github.com/DutchSailor/GIS2BIM/wiki/Gebruikshandleiding
