### ISSUE TITLE
Topografie geroteerd

### ISSUE THREAD

**Issue by erfan-wubbenchan** [DutchSailor/GIS2BIM#32]
Hi Maarten,

Ik ben momenteel Gis2BIM aan het uitproberen. 
Eerste indruk is dat het een super handige tool is om alle stedenbouwkundige randvoorwaarden met 1 tool op te halen!

Bij het testen loop ik tegen twee punten aan, namelijk:

1. bij het draaien van de script voor topografie, krijg ik de googlemaps afbeelding gedraaid t.o.v. de rest van de onderleggers en massa's. Weet jij waar dat aan ligt en hoe we dit kunnen oplossen. De andere onderleggers komen goed uit.
2. Ik heb geprobeerd om het materiaal van de bebouwingen aan te passen, maar deze lijkt gelocked te zijn vanuit de script. Is het mogelijk om deze open te stellen voor wijzigingen en zo ja, waar kan ik dat doen.

Graag hoor ik hoe hiermee om te gaan. Alvast bedankt.

Groeten,
Erfan Zoakman

**Comment by DutchSailor** [comment]
Hoi Erfan,

Revit heeft soms problemen met de orientatie van de afbeelding. Je kunt GIS2BIM_ImageRotateFlip gebruiken om dat te corrigeren. 
![image](https://user-images.githubusercontent.com/30430941/204384980-fa6694b1-8538-4750-9b3d-d520a99dba66.png)
