### ISSUE TITLE
1 - Kadastrale grenzen (OGC WFS) geeft geen output

### ISSUE THREAD

**Issue by CverkaikDHME** [DutchSailor/GIS2BIM#33]
De response van dit stuk van de node "GIS2BIM_NetherlandsGeoservicesLibrary" geeft een null als de eerste output verbonden is met "GIS2BIM_WebrequestWMS" 
Sommige andere outputs lijken ook gebroken te zijn, maar andere zoals "AHN3" en "Luchtfoto2020" lijkt wel te werken.

Als deze node in python wordt gezet in dynamo krijg ik de volgende error:

Warning: IronPythonEvaluator.EvaluateIronPythonScript operation failed. 
Traceback (most recent call last):
  File "<string>", line 15, in <module>
ValueError: Parameter is not valid.

Edit:
Het lijkt er op dat alle WFS services van deze node niet werken

**Comment by DutchSailor** [comment]
Heb je een screenshot? met de input en output?

**Comment by CverkaikDHME** [comment]
![screenshot GIS](https://user-images.githubusercontent.com/116566778/205270618-55286875-7fb0-4ada-bf24-6226a1a05833.png)

Bij deze de screenshot, sommige outputs doen het wel maar het lijkt er echt op dat de WFS url's die gegenereerd worden niet werken.

**Comment by DutchSailor** [comment]
Dank voor je reactie. Kun je je dynamoscript opsturen? Dan kijk ik er even naar.

**Comment by CverkaikDHME** [comment]
Bij deze het script! Alvast bedankt
[Generate site image short version.zip](https://github.com/DutchSailor/GIS2BIM/files/10184048/Generate.site.image.short.version.zip)

**Comment by DutchSailor** [comment]
WMS staat voor Web Map Service. Dit is een Raster formaat. de WebrequestWMS werkt alleen bij een WMS.

Degene die niet werken zijn WFS-services. Dat zijn vectorformaten. Dus lijnen etc. Je hebt daar andere nodes voor nodig om uit te lezen.
https://github.com/DutchSailor/GIS2BIM/wiki/Workflows-2.x-Nederland

Hier kun je voorbeeldscripts downloaden. Ook waar een WFS inzit.
