### ISSUE TITLE
links naar AHN3

### ISSUE THREAD

**Issue by arjan1987** [DutchSailor/GIS2BIM#36]
Hoi Maarten,

Sinds een tijdje werkt bij mij de AHN3 import niet meer. Ik heb uiteraard eerst geprobeerd om alles te updaten naar de laatste versie maar dat werkte helaas niet. 
Volgens mij heb ik het op kunnen lossen door de link in het script "GIS2BIM_AHN3toPoints" aan te passen naar https://service.pdok.nl/rws/ahn3/wcs/v1_0?.

Klopt het dat dit niet verwerkt is in meest recente versie?

Bij voorbaat dank voor je reactie!
Arjan

**Comment by DrLicor** [comment]
Hey Arjen,

Wij liepen hier inderdaad ook tegenaan. Bedankt voor het uitzoeken en plaatsen van de fix. 
Superfijn als webadressen van databases veranderen ;)
