### ISSUE TITLE
3d bag revit 2024

### ISSUE THREAD

**Issue by MariaStuart** [DutchSailor/GIS2BIM#37]
Is het dynamo script 3d bag al getest met Revit 2024?
Ik krijg namelijk een foutmelding bij Mesh.ImportFile. 
![2023-05-26 17_13_47-Dynamo](https://github.com/DutchSailor/GIS2BIM/assets/28647653/a6e407e5-e991-4dfb-86fc-a57693ce8a20)

**Comment by DutchSailor** [comment]
Vandaag hebben we getest met Revit 2024. Je moet versie 4.0 van de Mesh Toolkit gebruiken. Dan gaat het goed.
Versie 3.0 werkt niet om onduidelijke redenen
