### ISSUE TITLE
GIS2BIM scripts werken niet meer

### ISSUE THREAD

**Issue by DDO-dp83** [DutchSailor/GIS2BIM#38]
Hallo Maarten,

Sinds een tijde werken onze scripts van GIS2BIM niet meer, we hebben recent ook geen aanpassingen gedaan aan de scripts. Ik heb ergens al voorbij zien komen dat het mogelijk aan de weblink in bepaalde nodes kan liggen, is hier over iets bekend bij jullie? Ik hoor graag of er al een oplossing/update is waarin alles weer werkt!

Bij voorbaat dank en met vriendelijk groet,

Daan

**Comment by DutchSailor** [comment]
Er is een nieuwe versie! 0.12.2. Hier zijn de servernamen geupdate. Zowel voor 3D BAG, kadaster enzovoorts.
