### ISSUE TITLE
3D-BAG gebouwen komen niet meer binnen

### ISSUE THREAD

**Issue by DrLicor** [DutchSailor/GIS2BIM#39]
De webrequest vanuit de gebouwen loopt uit op foutmelding waardoor er geen mesh geimporteerd wordt.
Ik kon zo snel niet iets vinden in de documentatie van 3D-bag dat er iets is veranderd, iemand anders meer geluk?

**Comment by DutchSailor** [comment]
Er is inderdaad het e.e.a. veranderd in de servers.
Download de laatste versie van het script via deze link: https://github.com/DutchSailor/GIS2BIM/tree/master/supportfiles/Workflows2x%20Nederland/Workflows2x%20Nederland

**Comment by DutchSailor** [comment]
Bij gebruik van Revit 2024 moet je de Mesh Toolkit 3.0 gebruiken.
