### ISSUE TITLE
GIS2BIM.downloadBGTdata object -> string

### ISSUE THREAD

**Issue by jochem25** [DutchSailor/GIS2BIM#5]
de node GIS2BIM.downloadBGTdata geeft een object terug en bgt2d vraagt om een string.
Ik moest er "string from object" tussen zetten om het werkend te krijgen.
Misschien aanpassen in de node GIS2BIM.downloadBGTdata?

**Comment by DutchSailor** [comment]
Beste Jochem, dank! Ik heb het aangepast in versie 0.5. Deze komt medio januari uit.
